name: OpenSilver Build
env:
  next-release-version: '1.3.0'
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - develop
jobs:
  OpenSilver-Build:
    #We should not run these steps on the forks by default.
    #if: github.repository_owner == 'OpenSilver'
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.1
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.100'
      - name: Clone OpenSilver repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Restore teamdev.licenses
        run: 'echo "$TEAMDEV_LICENSE" > ./src/Simulator/Simulator/teamdev.licenses'
        shell: bash
        env:
          TEAMDEV_LICENSE: ${{secrets.TEAMDEV_LICENSE}}
      - name: Format Version Suffix
        id: format-suffix
        run: echo "::set-output name=suffix::$(date +'%Y-%m-%d-%H%M%S')-${{ env.GITHUB_SHA_SHORT }}"
      - name: Format Package Version
        id: format-version
        run: echo "::set-output name=version::${{ env.next-release-version }}-preview-${{ steps.format-suffix.outputs.suffix }}"
      - name: Build and Pack NuGet packages
        working-directory: build/BatFiles
        run: |
          ./SL_Build.bat ${{ steps.format-version.outputs.version }}
      - uses: actions/upload-artifact@v2
        with:
          name: OpenSilver
          path: "build/output/OpenSilver"
      - name: Upload packages
        run: |
           dotnet nuget push "build\output\OpenSilver\*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER_PART }}/index.json
      - name: Upload packages to MyGet
        run: |
           dotnet nuget push "build\output\OpenSilver\*.nupkg" -k ${{ secrets.MYGET_TEMP_TOKEN }} -s https://www.myget.org/F/opensilver-temp/api/v2/package     
